[package]
name = "clipaha-rs"
authors = ["Lukas Söder"]
readme = "./README.md"
license = "Apache-2.0"
repository= "https://github.com/rynoxx/clipaha-rs"
version = "0.9.0"
edition = "2021"

[dependencies]
argon2 = "0.5.0"
